name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean compile --file pom.xml

      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Package
        run: mvn -B package --file pom.xml

      - name: Run CLI benchmarks (optional, for empirical)
        run: |
          mkdir -p performance-plots
          mvn exec:java -Dexec.mainClass="org.example.cli.BenchmarkRunner" -Dexec.args="100 random selection" > performance-plots/benchmark.csv  # Example small benchmark (add more if needed)

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: performance-plots/benchmark.csv

      - name: Update dependency graph (optional, for security)
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6  # Dependabot alerts